### PR TITLE
Added the deactivate users.

### PR DESCRIPTION
**Pull request by robherba**
**Steps to test**

-Create a user node.
-Go to /users.
-Check if the function deactivate users run successfully.

### CODE REVIEW

**Comment by robherba** [comment]
@kporras07

**Comment by kporras07** [comment]
@josue2591 test this please.

**Comment by josue2591** [comment]
@rohernandez It looks fine to me, @kporras07 is this ready to merge?

**Comment by kporras07** [comment]
:shipit:

**Pull request merged**
