### PR TITLE
22: Projects listing

### PR DESCRIPTION
**Pull request by robherba**
**Steps to test**
- See if views has been added successfully.
- Create projects nodes to test.

**DoD**
- As an administrator I want to go /projects and get a table with a list of Project Name, Client Names.
- In that view, I need to have direct links to edit projects.

[issue link](https://github.com/ManatiCR/manatime/issues/22)

### CODE REVIEW

**Comment by kporras07** [comment]
@rohernandez missing edit link in view, missing client column name.

**Comment by robherba** [comment]
Changes has been applied.

**Comment by robherba** [comment]
Changes has been applied, needs review.

**Comment by josue2591** [comment]
It looks rigth to me, wait what @kporras07 is going to say about it.

**Comment by josue2591** [comment]
The custom permissions are fine.

**Comment by kporras07** [comment]
:shipit:

**Pull request merged**
