### PR TITLE
10: Users.

### PR DESCRIPTION
**Pull request by josue2591**
**Steps to test.**
- Verify field_weekly_hours was added to the feature manatime_feature_field_bases sucesfully.
- Check if the manatime_feature_users works properly. 

**DoD:**
- As an administrator I should be able to go to admin/people/add and add a new user with the described fields
- As an administrator, I should be able to view a user (no themed) and click on the Edit tab and update that user.

[Issue link](https://github.com/ManatiCR/manatime/issues/10)

### CODE REVIEW

**Comment by robherba** [comment]
@kporras07

**Comment by robherba** [comment]
Code looks ok for me.

**Comment by kporras07** [comment]
Code looks ok, doing functional review.

**Comment by kporras07** [comment]
:shipit:

**Pull request merged**
